spring:
  application:
    name: api-gateway

server:
  port: 8007

zuul:
  routes:
    api-a:
      path: /user-service/**
      serviceId: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
