spring:
  application:
    name: api-gateway

server:
  port: 8007
zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service2

ribbon:
  eureka:
    enabled: true
user-service2:
  ribbon:
    listOfServers: http://localhost:8003/,http://localhost:8004/

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8002/eureka/
